fos_rest:
    body_listener: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: 'force'
        mime_types:
            json: [ 'application/json; charset=UTF-8', 'application/json' ]
        formats:
            json: true
    exception:
        serializer_error_renderer: true
